apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: ghcr.io/apsega/demo-app
  newName: ghcr.io/apsega/demo-app
  newTag: 33ac470f564b16f89834de3e3c8bb069b0184036
